### ISSUE TITLE
death bunny is deadly, closure is needed

### ISSUE THREAD

**Issue by DarkMarmot** [ohmubus/seele#2]
replace the the call to _cyanideTooth with a closure that returns a method like

var name, agent;

```
function(){
   return function(){
      _cyanideTooth(name, agent); // capture in closure outside
   };
} 
```

now a destroy method is passed in, any object can call destroy(); and it runs with corrects args in correct context always.

**Comment by enlore** [comment]
`_falseTooth` now binds `name` and `_agent` (the plugin instance) via closure and delegates to `_cyanideCapsule`.
